### ISSUE TITLE
What do you think about changing "edit profile" to "hack profile"?

### ISSUE THREAD

**Issue by b3yond** [Chronister/mastodon#11]
Hi,

as cybre.space is dwelling into the topic of everything #cyber and hacky, I think it would be nice to expand the theme on more elements of the UI.

replacing the word "edit" with "hack" in some places seems to be one of the more obvious ideas to me - the terms are associated and imo "hack" doesn't obscure the meaning ( @Chronister seems think different, join the discussion either here or at https://cybre.space/@chr/1106015 )

What do you think? the more perspectives we have on this, the better the decision will be.

b3yond

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by chr-1x** [comment]
for posterity, I suggested "Edit identity" instead but am open to other ideas

**Comment by compufox** [comment]
Maybe like self.hack() or edit(self) 🤷

**Comment by b3yond** [comment]
what about self.edit() ?

**Comment by compufox** [comment]
Yeah, I like that!

**Comment by claiire** [comment]
I'd propose `$ vim ~/.profile` but I really like the other proposals here too!

**Comment by chr-1x** [comment]
Poll here: https://goo.gl/forms/Jv3sHnNthYqQzPb82

Closing tomorrow at this time

**Comment by nightpool** [comment]
if we start replacing verbs with "hack", I don't think we'll ever stop.

**Comment by chr-1x** [comment]
Poll's closed. It'll be edit ~/.profile

**Comment by nightpool** [comment]
closed in ... one of those changes. i dunno. it probably got rewritten into 36d157b05cde99fe8dd9e44fd057157dfe4505b4
