### ISSUE TITLE
in-reply-to box color is blurgh

### ISSUE THREAD

**Issue by nightpool** [Chronister/mastodon#13]
![image](https://user-images.githubusercontent.com/233815/30065438-cefa7ea6-9222-11e7-9f12-ceb9705dedfa.png)

guessing this was fa3b262

**Comment by nightpool** [comment]
more bad colors:

![image](https://user-images.githubusercontent.com/233815/30069959-0f6bc924-9230-11e7-9e50-a500f5298a2b.png)
![image](https://user-images.githubusercontent.com/233815/30069969-143b709e-9230-11e7-9fc8-6b1407027ce7.png)

**Comment by chr-1x** [comment]
thsi was fixed in 1f36323765eef2f07eb09bc0451148d5dbdd5399  and 3e99566cda82012e2a1655c22bde0c2fb199f847
