### ISSUE TITLE
Public prometheus/stats

### ISSUE THREAD

**Issue by shanemhansen** [Chronister/mastodon#22]
Any interest in incorporating a way for people to view instance performance? Like how gitlab has public data? https://monitor.gitlab.net/d/000000021/elasticsearch-cluster-stats?orgId=1

I just think it would be cool to be in the open as your instance scales. Happy to help set it up if there's interest.

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
status.cybre.space

**Comment by shanemhansen** [comment]
Thanks, that is amazing!
