### ISSUE TITLE
Scrolling issue in the New Toot column - may be instance-specific?

### ISSUE THREAD

**Issue by Cassolotl** [Chronister/mastodon#6]
Basically, [this issue](https://github.com/tootsuite/mastodon/issues/2401)!

Me:

>If I'm writing a post that's kinda longish, when I'm done and I go to choose a privacy setting, the menu gets lost under the bottom of the page and there's no scrollbar and I can't scroll.

Someone else:

> It may be that the instance you are on has customized the CSS which isn't allowing for scrolling. The CSS for .drawer__inner class should have the following CSS, which should allow it to scroll:
> 
> overflow: hidden;
> overflow-y: auto;
>
> If that overflow-y value was overridden, then it's possible that could explain why you are not able to scroll.

What d'you reckon?

* * * *

- [Yup] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [???] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
yeah this is our fault. It has to do with the styles that were added to
make that column transparent. We probably need to add another wrapper or
add some styles to the outer column to get this working.

**Comment by Cassolotl** [comment]
Cool cool - I will close the issue on the main Mastodon issue list. :) Thanks for the speedy response!

**Comment by nightpool** [comment]
Did this get fixed or it still an issue?

**Comment by Cassolotl** [comment]
It is fixed! :) Thank you!
