### ISSUE TITLE
Small update on /about/more needed

### ISSUE THREAD

**Issue by Cassolotl** [Chronister/mastodon#7]
This is a really small thing, but:

>Provide appropriate content warnings on potentially sensitive posts and use NSFW tags liberally on adult images, flashing gifs/videos, and potentially spoiling content.

Animated gifs can be autopaused now, so perhaps the requirement to put them behind a NSFW thing could be removed from that rule?

* * * *

- [Yes] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
+1 from me.

**Comment by chr-1x** [comment]
done
