### ISSUE TITLE
What are your thoughts on... the ambassador bot?

### ISSUE THREAD

**Issue by Cassolotl** [Chronister/mastodon#8]
https://github.com/mbilokonsky/ambassador

I like them and I like cybre.space so I think it could be nice if we had one of these. What do you think?

* * * *

- [There was only one open issue and it was me. XD] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [N/A] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by chr-1x** [comment]
I 'm willing to consider it as long as there's no major objections from anyone

**Comment by Cassolotl** [comment]
Cool! Perhaps I will make a poll for cybre.space members to see if anyone objects or something. Feel free to do that instead if you are impatient - it's 1am where I am so I should go to sleep. :P

**Comment by nightpool** [comment]
i'm not a huge fan. I would like to see statistics on the cybrespace toot
population before firming up my opinion though. What are some reasonable
thresholds, and given those thresholds how many pings would it relay per
day? 10 florps? 15 florps? more?

and how many users? It would be kinda a shitty ambassador if it was full of
just 1 or 2 popular user's accounts.

**Comment by Cassolotl** [comment]
I share these concerns too. It would be really good if the admin could choose how many posts it did per day and how they were spaced through the day, if that's the right word.

(Edit: [spacing posts through the day](https://github.com/mbilokonsky/ambassador/issues/7) is a planned feature!)

Re: florps, this is what the ambassador bot's blurb says:

> So we do two things here:
> 
> 1. Compute our fav threshold. Grab all public toots that have received more than 1 fav over the past 30 days. Average the fav counts for those toots. This is our threshold.
> 2. Find any public toots created within the past five days which have received at least that many favs.
> 
> Goal here is that this sets a pretty high bar (favs over 30 days) and applies it to only the past 5 days. It's an aggressive filter, but it's also a sliding window. If you have a bunch of super popular toots on your instance, they'll skew the curve - but only for a month or so, and this will be normalized if you have a lot of activity. Generally things will even out over time.
> 
> I am not, btw, a database expert - I pieced this query together through trial-and-error and if you want to propose an optimization I am all ears.

I did notice that when it was used on a very small, very new instance, it mostly reposted the same person over and over. That was not much fun. But as the instance got bigger and more connected, it got more diverse.

**Comment by nightpool** [comment]
@cassolotl are there good examples of the bot in practice? can you link
other ambassador accounts?

**Comment by Cassolotl** [comment]
Here's the one for a.weirder.earth, an instance run by the person who made the ambassador bot: https://a.weirder.earth/@ambassador That one is quite varied, and the instance has 158 members.

Here's one for mst3k.interlinked.me: https://mst3k.interlinked.me/@AmbassadorBot That one's a lot less varied and the instance has 81 members.

Those are the only two I'm aware of!

**Comment by Cassolotl** [comment]
I've started [a poll](http://www.strawpoll.me/12842129) and here's [the results page](http://www.strawpoll.me/12842129/r).

**Comment by nightpool** [comment]
Yeah, the mst3k one was the one I was thinking of. Good to see that the
flagship one is doing well though!

**Comment by Cassolotl** [comment]
So, I ran a poll - I guess it's been up a little less than a day. [Here's the results](http://www.strawpoll.me/12842129/r) so far:

![screen shot 2017-04-29 at 10 37 46](https://cloud.githubusercontent.com/assets/6607512/25554553/e9612c2e-2cc7-11e7-953c-332d1ad36ce1.png)

Around late evening UK time, the busiest time while I'm awake, I asked why people who don't want an ambassador bot don't want one, but got no replies! So, I don't know if we can say if anyone has major objections, but 1 in 5 people objected in the poll.

**Comment by nightpool** [comment]
The ambassador bot was implemented for a couple of weeks, but recently got removed pending some selectivity changes. I'm going to close this issue as a record of the historical discussion, but feel free to open a new one!
